import React, {useEffect, useState, useContext} from 'react';

import {
  handleRegister,
  handleSignIn,
  handleListenUserProfile,
  handleStreakRewards,
  handleSpotifyService,
  handleAppleMusicService,
  handleAddStory,
  handleSearchUsers,
  handleRetrieveStory,
  handleSetChat,
  handleRetrieveChats,
  handleRetrieveChat,
  handleSubmitChat,
  handleRetrieveChats1,
  handleRetrieveUser,
  handleToggleProfileVisibility,
  handleToggleFollowUser,
  handleFCMToken,
  handleBuildProfile,
  handleAppendTransactions,
  handleUpdateTransaction,
  handleMigrateTransaction,
  handleAppendTRAKLIST,
} from './hooks';

export const useFirebase = () => {
  return {
    handleRegister,
    handleSignIn,
    handleListenUserProfile,
    handleStreakRewards,
    handleSpotifyService,
    handleAppleMusicService,
    handleAddStory,
    handleSearchUsers,
    handleRetrieveStory,
    handleSetChat,
    handleRetrieveChats,
    handleRetrieveChats1,
    handleRetrieveChat,
    handleSubmitChat,
    handleRetrieveUser,
    handleToggleProfileVisibility,
    handleToggleFollowUser,
    handleFCMToken,
    handleBuildProfile,
    handleAppendTransactions,
    handleUpdateTransaction,
    handleMigrateTransaction,
    handleAppendTRAKLIST,
  };
};
