[project]
name = "trx-00"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.nft-trait]
path = "contracts/nft-trait.clar"
depends_on = []

[contracts.trx-00]
path = "contracts/trx-00.clar"
depends_on = ["nft-trait"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
